services:
  mongo:
    image: mongo:7
    container_name: freteja-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: freteja
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: freteja-api
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      SERVER_PORT: 8080
      MONGODB_URI: mongodb://mongo:27017/freteja
      JWT_SECRET: change-me-super-secret
      JWT_EXPIRATION_MS: 86400000
      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "8080:8080"

  # Opcional para ver o banco em UI web
  mongo-express:
    image: mongo-express:1.0.2
    container_name: freteja-mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"

volumes:
  mongo_data:

