services:
  mongo:
    image: mongo:6
    # remova container_name para evitar conflitos de nome
    # container_name: freteja-mongo
    restart: unless-stopped
    command: ["--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # REMOVER o healthcheck
    # healthcheck:
    #   test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  api:
    build: .
    # remova container_name para evitar conflitos
    # container_name: freteja-api
    depends_on:
      # mudar para "service_started", já que não há healthcheck
      mongo:
        condition: service_started
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MONGODB_URI: ${MONGODB_URI}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
    ports:
      - "${SERVER_PORT}:8080"
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1
    # container_name: freteja-me
    depends_on:
      mongo:
        condition: service_started
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mongo_data: