version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: freteja-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: freteja
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: freteja-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
