server:
  port: ${SERVER_PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo:27017/freteja}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: ${JWT_SECRET:dev-secret-change-me}
    expiration: ${JWT_EXPIRATION_MS:86400000} # 24h em ms

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

